from backend.agents.testcase_agent import TestcaseAgent
from backend.ai.prompt_manager.prompt_manager import PromptManager
from backend.generators.testcase_formatter import TestCaseFormatter


class TaskExecutor:
    """
    Executes AI tasks generated by the Analysis Planner.
    """

    @staticmethod
    def execute(
        task: dict,
        repository_context: dict,
        code: str,
    ):

        print(
            f"\nExecuting Task {task['task_id']} : "
            f"{task['method']} {task['path']}"
        )

        prompt = PromptManager.testcase(
            repository_context=repository_context,
            file_name=repository_context.get(
                "current_file",
                "",
            ),
            code=code,
        )

        response = TestcaseAgent.generate(
            prompt=prompt
        )

        formatted = TestCaseFormatter.format(
            response
        )

        task["status"] = "Completed"

        task["testcases"] = formatted

        return task